name: Update M3U8 Link

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install puppeteer
      - run: node update.js
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Auto-update token via Puppeteer"
          file_pattern: playlist.m3u8
